### Obtener todas las películas
GET http://localhost:1234/movies

### Obtener una pelicula por ID
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=drama

### Crear una película
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una película 
PATCH http://localhost:1234/movies/2ff4dee1-5855-43e9-b4a1-61679fd343f4
Content-Type: application/json

{
  "year": 1971
}
